/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cozy developer workspace 3d model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/cozy developer workspace 3d model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_94db7fa7-684a-4b0d-b780-84e14ffd648d'].geometry} material={materials['tripo_material_94db7fa7-684a-4b0d-b780-84e14ffd648d']} />
    </group>
  )
}

useGLTF.preload('/models/cozy developer workspace 3d model.glb')
